---

- hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - config_vars.yml
  tasks:

    # Docker Driver
    - block:
 
        - name: Destroy molecule Docker instance(s)
          docker_container:
            name: "{{ item.name }}"
            state: absent
            force_kill: "{{ item.force_kill | default(True) }}"
          with_items: "{{ molecule_yml.platforms }}"

      when: molecule_driver_name == 'docker'

    # Vagrant Driver
    - block:

        - name: Destroy molecule Vagrant instance(s)
          molecule_vagrant:
            instance_name: "{{ item.name }}"
            platform_box: "{{ vagrant_base_image[molecule_target_distro] }}"
            state: destroy
          register: server
          with_items: "{{ molecule_yml.platforms }}"

        # Mandatory configuration for Molecule to function.

        - name: Populate instance config
          set_fact:
            instance_conf: {}

        - name: Dump instance config
          copy:
            # Workaround for Ansible 2.2.
            # https://github.com/ansible/ansible/issues/20885
            content: "{{ instance_conf | to_json | from_json | molecule_to_yaml | molecule_header }}"
            dest: "{{ molecule_instance_config }}"
          when: server.changed | bool

      when: molecule_driver_name == 'vagrant'
