---

scenario:
  name: swarm-cluster

driver:
  name: "${MOLECULE_DRIVER_NAME:-docker}"   # The Molecule Driver can be overriden using
                                            # the MOLECULE_DRIVER_NAME environment variables.
dependency:
  name: galaxy

platforms:

  - name: ansible-dockerswarm-1
    groups:
      - docker_engine
      - docker_swarm_manager

  - name: ansible-dockerswarm-2
    groups:
      - docker_engine
      - docker_swarm_manager

  - name: ansible-dockerswarm-3
    groups:
      - docker_engine
      - docker_swarm_worker

provisioner:
  name: ansible
  options:
    diff: True
    v: True
  playbooks:
    create: ../common/create.yml
    destroy: ../common/destroy.yml
  lint:
    name: ansible-lint

lint:
  name: yamllint   # Will use the rules defined in .yamllint

verifier:
  name: testinfra
  lint:
    name: flake8
